<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Icons\AplicationMain.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="View\Frm.cs~RF538e29d.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icons\AplicationMain.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.WindowsForms" Version="2.1.2" />
  </ItemGroup>

</Project>